package org.web.vo;

public class Good {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.subject_name
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.subject_code
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    private String subjectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.subject_desc
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    private String subjectDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.subject_name
     *
     * @return the value of goods.subject_name
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.subject_name
     *
     * @param subjectName the value for goods.subject_name
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.subject_code
     *
     * @return the value of goods.subject_code
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public String getSubjectCode() {
        return subjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.subject_code
     *
     * @param subjectCode the value for goods.subject_code
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode == null ? null : subjectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.subject_desc
     *
     * @return the value of goods.subject_desc
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public String getSubjectDesc() {
        return subjectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.subject_desc
     *
     * @param subjectDesc the value for goods.subject_desc
     *
     * @mbg.generated Fri Aug 16 16:52:32 CST 2019
     */
    public void setSubjectDesc(String subjectDesc) {
        this.subjectDesc = subjectDesc == null ? null : subjectDesc.trim();
    }
}